//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uretim_Kalite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGEM_KALITE_PERSONEL
    {
        public int ID { get; set; }
        public string ADSOYAD { get; set; }
    }
}
