//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uretim_Kalite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EGEM2021Entities1 : DbContext
    {
        public EGEM2021Entities1()
            : base("name=EGEM2021Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EGEM_ESNEK_DILIMLEME_KALITE> EGEM_ESNEK_DILIMLEME_KALITE { get; set; }
        public virtual DbSet<EGEM_ESNEK_LAMINASYON_KALITE> EGEM_ESNEK_LAMINASYON_KALITE { get; set; }
        public virtual DbSet<EGEM_GRAVUR_KALITE> EGEM_GRAVUR_KALITE { get; set; }
        public virtual DbSet<EGEM_OFSET_BASKI_KALITE> EGEM_OFSET_BASKI_KALITE { get; set; }
        public virtual DbSet<EGEM_OFSET_BITIRME_KALITE> EGEM_OFSET_BITIRME_KALITE { get; set; }
        public virtual DbSet<EGEM_ESNEK_BASKI_KALITE> EGEM_ESNEK_BASKI_KALITE { get; set; }
        public virtual DbSet<EGEM_GRAVUR_KALITE_SIPARIS> EGEM_GRAVUR_KALITE_SIPARIS { get; set; }
        public virtual DbSet<EGEM_KALITE_USER> EGEM_KALITE_USER { get; set; }
        public virtual DbSet<EGEM_KALITE_PERSONEL> EGEM_KALITE_PERSONEL { get; set; }
        public virtual DbSet<EGEM_ESNEK_BASKI_KALITENOKIMAJ> EGEM_ESNEK_BASKI_KALITENOKIMAJ { get; set; }
        public virtual DbSet<EGEM_ESNEK_DILIMLEME_KALITENOKIMAJ> EGEM_ESNEK_DILIMLEME_KALITENOKIMAJ { get; set; }
        public virtual DbSet<EGEM_ESNEK_LAMINASYON_KALITENOKIMAJ> EGEM_ESNEK_LAMINASYON_KALITENOKIMAJ { get; set; }
        public virtual DbSet<EGEM_GRAVUR_KALITENOKIMAJ> EGEM_GRAVUR_KALITENOKIMAJ { get; set; }
        public virtual DbSet<EGEM_OFSETBASKI_KALITENOKIMAJ> EGEM_OFSETBASKI_KALITENOKIMAJ { get; set; }
        public virtual DbSet<EGEM_OFSETBITIRME_KALITENOKIMAJ> EGEM_OFSETBITIRME_KALITENOKIMAJ { get; set; }
    }
}
